# Generated by Django 5.2.8 on 2026-01-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='required',
            field=models.BooleanField(default=True, help_text='Whether this field is required'),
        ),
    ]
