# Generated by Django 5.2.8 on 2026-03-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_dynamicfield_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
