# Generated by Django 5.2.8 on 2026-03-02 05:02

from django.db import migrations
from django.db.models import F


def copy_data_to_emp_data(apps, schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    for employee in Employee.objects.all():
        employee.emp_data = employee.data
        employee.save()


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0003_employee_emp_data'),
    ]

    operations = [
        migrations.RunPython(copy_data_to_emp_data),
    ]
