# Generated by Django 5.2.8 on 2026-03-02 05:08

from django.db import migrations
from django.db.models import F

def copy_data_to_emp_data(apps, schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    Employee.objects.update(emp_data=F('data'))

class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0003_employee_emp_data'),
    ]

    operations = [
        migrations.RunPython(copy_data_to_emp_data),
    ]