# Generated by Django 5.2.8 on 2026-03-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20260302_1032'),
        ('employee', '0004_auto_20260302_1038'),
    ]

    operations = [
    ]
